### ISSUE TITLE
?

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-wordpress#1]
Ciao @salvorapi e @umbros!

Ma questo?

https://github.com/italia/spid-wordpress-plugin

Ed in ogni caso, vero che i commit che vediamo qui (o là) sono di esempio e possiamo sovrascrivere con [questo](https://github.com/ItalianLinuxSociety/spid-wordpress/tree/9b95f40d29921a1a640f6c0f3d02f1192e77cbae)?

**Comment by valerio-bozzolan** [comment]
...o per qualche motivo si preferisce un merge con [questo](https://github.com/lvps/spid-wordpress/tree/3163bee2d37fe4aefd89c35f2fab6f637c51fccf)? Nel caso, fare merge del #2.

**Comment by valerio-bozzolan** [comment]
O___O Ma come c*** è stato fatto questo merge? Perchè si deve cancellare un anno di cronologia?

**Comment by salvorapi** [comment]
Ops, non so cosa sia successo.
Ho seguito la guida di Github ma evidentemente qualcosa non è andato.
Vedo come rimediare.
