### ISSUE TITLE
SimpleSAMLPHP Path

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-wordpress#3]
Fixare la pagina di settings che ora dà `Option simplesamlphp_path unsupported!`.

**Comment by valerio-bozzolan** [comment]
@salvorapi fra l'altro, perchè questa cosa dovrebbe poter essere modificabile dal database invece che dal `wp-config.php` attraverso la costante `WP_SIMPLESAML_DIR`?

Correggetemi se sbaglio ma variare quel percorso è una cosa che può fare solo chi ha accesso ai file, non è una cosa che può fare un utente che ha accesso solo al frontend. In tal caso tanto vale farlo solo dal `wp-config.php`.

**Comment by lvps** [comment]
Ha senso che sia configurabile dal db: se devi scrivere una guida su come fare o spiegarlo per telefono a qualcuno, probabilmente è più facile così che dire "vai a modificare wp-config.php" (Dove? Come? Chi ha le credenziali dell'FTP? Dov'è hostato il sito? etc...)

**Comment by valerio-bozzolan** [comment]
@lvps Sì OK, ma in ogni caso hai bisogno dell'accesso ai file per far sì che quel percorso esista.

**Comment by lvps** [comment]
@valerio-bozzolan sì ok, ma sto immaginando la classica situazione in cui tutto il sito l'ha installato e configurato 12 anni prima "un tecnico" o qualche altra misteriosa entità scomparsa da 11 anni, poi in qualche modo appare un'installazione di sistema di SimpleSPIDPHP dal nulla (probabilmente è lì da 12 anni anche quella) e si decide di utilizzarla... fai prima a dire "impostate il percorso dal pannello admin" o "inseguite sistemisti eterei irreperibili da 11 anni per farvi dare la password dell'FTP"? asd

C'è un leggero rischio di sicurezza tramite inclusione di file arbitrari... che devono comunque trovarsi sul server. Mettiamo un controllo in modo che il file selezionato abbia permessi di esecuzione, per escludere quelli nelle directory "upload" sparse in giro, anche se gli host pezzenti mettono permessi 777 a tutto di default?

**Comment by valerio-bozzolan** [comment]
:1st_place_medal:  Premio casistica senza alcun senso e che introdurrà solo CVE.

**Comment by salvorapi** [comment]
Secondo me non è da sottovalutare quello che ha detto @lvps.
Una volta che effettui l'integrazione di SPID devi fare attenzione al discorso sicurezza e quindi indicare le versioni minime di WordPress e SimpleSAMLPHP insieme a delle best practices da seguire. 

Io immaginavo una situazione in cui il plugin non si abilita se non sono soddisfatti alcuni requisiti (ad esempio, HTTPS attivo).

Cosa ne pensate?

SR

**Comment by valerio-bozzolan** [comment]
@salvorapi Aspetta, il dubbio era solo questo: È utile o complessifica e peggiora solo la sicurezza del plugin la creazione di un'interfaccia utente in cui chiedere il percorso di SimpleSamlPHP?

Perchè non basta la banale costante in `wp-config.php` modificabile per definizione solo da chi ha accesso ai file?

Così come solo chi ha accesso ai file può modificare la configurazione di SimpleSpidPHP, credo sia ragionevole che _solo_ chi abbia accesso ai file possa dire a WordPress dove sia fisicamente tale configurazione. Fare un `require` di un percorso pigliato da database non mi sembra adatto senza un buon motivo.

**Comment by salvorapi** [comment]
Pensandoci bene potrebbe creare un "problema di sicurezza" impostare un parametro come il path di SimpleSAMLPhp tramite interfaccia web quindi per me va bene metterlo sul `wp-config.php`.
Per il parametro `authsource` e `mapping attributi` penso vada bene una configurazione lato admin.

Resta il fatto che dovremmo aggiungere un percorso di validazione della configurazione del plugin prima di attivarlo.

SR.

**Comment by valerio-bozzolan** [comment]
OK bene. Solo per fare ordine dedico a quest'altro discorso il #5.
